-- Rooms upsert from 'rooms (3).xlsx'
-- Idempotent — INSERT new rooms, UPDATE existing by id.
-- Does NOT delete rooms that exist in the DB but not in the Excel,
-- because mtg_rooms has ON DELETE CASCADE → bookings would get wiped.
-- Manually drop any obsolete rooms after reviewing what's left.

begin;

insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C001', 'ห้องมั่งคั่ง', 'https://drive.google.com/thumbnail?id=10q6Is9SZ1QGDEy471SXQ8tYE7rUNvSLU&sz=w400', 'Comets HQ', NULL, 'unavailable') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C002', 'ห้องร่ำรวย', 'https://drive.google.com/thumbnail?id=1RUO6VUiVMRwjJuMDT1aOgvGz5gsbh-yJ&sz=w400', 'Comets HQ', NULL, 'unavailable') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C003', 'ห้อง THE STAR', 'https://drive.google.com/thumbnail?id=13C8fGyApHz-ODPbpjoeJIaPAK2xI1JlR&sz=w400', 'Comets HQ', NULL, 'unavailable') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C004', 'ห้อง GALAXY', 'https://drive.google.com/thumbnail?id=17B6h4TRG6Thm-6aWIRiLoKlUXp4KUQzx&sz=w400', 'Comets HQ', NULL, 'unavailable') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C005', 'ห้องเพิ่มพูน', 'https://drive.google.com/thumbnail?id=16VAure0zTl9wtHTKh59cUF9d_jhld51A&sz=w400', 'Comets HQ', NULL, 'unavailable') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C006', 'ห้องประชุมชั้น 1', 'https://drive.google.com/thumbnail?id=12pgFRB5K4z3p5-KF85PlY9WqBaTxqGqC&sz=w400', 'Comets HQ', NULL, 'unavailable') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C007', 'ห้องโถงชั้น 1', 'https://drive.google.com/thumbnail?id=1AejxmAwOxMA9tP8qSjeFH1e0tdzycnDb&sz=w400', 'Comets HQ', NULL, 'unavailable') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C008', 'ห้อง NORTH STAR', 'https://drive.google.com/thumbnail?id=1XjVZoeUWx7N9yHRsYb7cxg7EfBVMALNe&sz=w400', 'Comets HQ', 12, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C009', 'ห้อง JUPITER', 'https://drive.google.com/thumbnail?id=1OExQY0oQ8FnX0V8MEIC5KhCDuUNVlXyh&sz=w400', 'Comets HQ', 7, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C010', 'ห้อง NEPTUNE', 'https://drive.google.com/thumbnail?id=13BAS_QgHnpo1lpPd_nQfeiFvGHRFWEbR&sz=w400', 'Comets HQ', 7, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C011', 'ห้องประชุมชั้น 3', 'https://drive.google.com/thumbnail?id=1gKN6QO0t3tgMxQ6bEGckGdAa_6iPyM1R&sz=w400', 'Comets HQ', NULL, 'unavailable') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C012', 'ห้อง MERCURY', 'https://drive.google.com/thumbnail?id=12GsU9JdDPmtm7xUHBv5i7d-HQqKhTLY-&sz=w400', 'Comets HQ', 6, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C013', 'ห้อง VENUS', 'https://drive.google.com/thumbnail?id=1B0AvA54-h5pkZatk52EoVmbxt-wYSPRe&sz=w400', 'Comets HQ', 6, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C014', 'ห้อง 2 B', 'https://drive.google.com/thumbnail?id=1omwiuV5KnC_xr7RBJxzdY892VAUKIQbX&sz=w400', 'ICT', NULL, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C015', 'ห้อง Color', 'https://drive.google.com/thumbnail?id=1tf8Ul4R-DBNbURNN7DwWrHgJ7YAxR0WA&sz=w400', 'ICT', NULL, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C016', 'ห้อง Innovation', 'https://drive.google.com/thumbnail?id=1166mPwY8440z-Cx_BI2R1VivDhJ-TCF8&sz=w400', 'ICT', NULL, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C017', 'ห้อง Tecnology room', 'https://drive.google.com/thumbnail?id=1qKNr2jJrdwBdzSFuOc2IOkPCToiwWnAg&sz=w400', 'ICT', NULL, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C018', 'ห้อง 2 A', 'https://drive.google.com/thumbnail?id=1A4IuVUQbqwuCCIGbVctYmqAodv6gFxiC&sz=w400', 'ICT', NULL, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C019', 'ห้อง LIVE', 'https://drive.google.com/thumbnail?id=1k424motLR0u43zfdcShIhn6CLrtzE6Cc&sz=w400', 'Comets HQ', NULL, 'unavailable') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C020', 'ห้อง The Lumi (3B)', 'https://drive.google.com/thumbnail?id=1OmDKXxALNjpRgrQ7XeTY-jBFy2TRd64U&sz=w400', 'Comets HQ', 14, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C021', 'ห้อง Glow Room (3B)', 'https://drive.google.com/thumbnail?id=14Ac1XBLw57IOMMZtb7CGpqoQ6d0i0Q50&sz=w400', 'Comets HQ', 7, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C022', 'ห้อง The Crystal Hall (3M)', 'https://drive.google.com/thumbnail?id=1hFJUiBN-7UM7I2nIrqkrdSt0bfHh64q-&sz=w400', 'Comets HQ', NULL, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C023', 'ห้อง How are you? (3A)', 'https://drive.google.com/thumbnail?id=1fWHCIKiYKw3ShYA16c5JXGaMAoIAYiVQ&sz=w400', 'Comets HQ', 6, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C024', 'ห้อง I’m fine (3A)', 'https://drive.google.com/thumbnail?id=1I2s9A1_utsCzq3dOEAXWoWY6HmO1sXxO&sz=w400', 'Comets HQ', 6, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C025', 'ห้อง Thank you (3A)', 'https://drive.google.com/thumbnail?id=1bzsoYVOBWKABTbyDKBXBpinpHSTWz6YV&sz=w400', 'Comets HQ', 1, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C026', 'ห้อง And you? (3A)', 'https://drive.google.com/thumbnail?id=1Rkv3K3Zq6TJBDbSP-G3n_ZZVarn_yEv9&sz=w400', 'Comets HQ', 1, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C027', 'ห้อง Hello (3B)', 'https://drive.google.com/thumbnail?id=1xIKJblP1iagewvp6GFujVZYs47U4viBB&sz=w400', 'Comets HQ', 6, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C028', 'ห้อง Daily (4A)', 'https://drive.google.com/thumbnail?id=1opmJstz_oKbhuc3hJoLnrWUD1SYQSQAI&sz=w400', 'Comets HQ', 1, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C029', 'ห้อง Life (4A)', 'https://drive.google.com/thumbnail?id=1hHiLvAbl3UBfK2rAdnHvGHm2RwcKQGhd&sz=w400', 'Comets HQ', 6, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C030', 'ห้อง Flow (4A)', 'https://drive.google.com/thumbnail?id=1F8P1gA-FTbeJKlbTEOed2kBg4kihIXY4&sz=w400', 'Comets HQ', 6, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C031', 'ห้อง The Pearl (4A)', 'https://drive.google.com/thumbnail?id=1UnodVHbDavlMxbADJyVC5gBsjMqnLRYO&sz=w400', 'Comets HQ', 14, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C032', 'ห้อง Opal Room (4A)', 'https://drive.google.com/thumbnail?id=1-DFiT5mpf5STdq5OvnC7xpbxcmR96h8G&sz=w400', 'Comets HQ', 7, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C033', 'ห้อง The Star (4A)', 'https://drive.google.com/thumbnail?id=1LaYgSVbkDhGB2D1Gbtgd0zjUt4vka3Pi&sz=w400', 'Comets HQ', 17, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C034', 'โต๊ะประชุม 3B3', 'https://drive.google.com/thumbnail?id=13pe-4Np40EWdSfCEjuHMQtF7IpulLNvZ&sz=w400', 'Comets HQ', 6, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C035', 'โต๊ะประชุม 3B4', 'https://drive.google.com/thumbnail?id=1KTqeSmIWjSAF8cZN6idBCrKBnCK8hvIG&sz=w400', 'Comets HQ', 6, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C036', 'ห้อง Welcome (ชั้น1)', 'https://drive.google.com/thumbnail?id=1sflJhwcq8OCdCGiM_U0zJK-mRDR5VEbJ&sz=w400', 'Comets HQ', 6, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C037', 'ห้อง The EDEN (4B)', 'https://drive.google.com/file/d/1ptKj7-HdxmNfPA4a8kY78HnYD7-A525A/view?usp=sharing', 'Comets HQ', NULL, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C038', 'ห้อง The bloom (4B)', 'https://drive.google.com/file/d/1YYylTZRAF6ehD1qpu0x-aZ4Y8QfWshEn/view?usp=sharing', 'Comets HQ', NULL, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C039', 'ห้อง Eva Room (4B)', 'https://drive.google.com/file/d/1p1jTWUJc3T-IR7gefNFyjSn6-NAENKdi/view?usp=sharing', 'Comets HQ', NULL, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C040', 'ห้องร้อยล้าน (4B)', 'https://drive.google.com/file/d/1sZ0OPS153RXCcFQ8PsJ36pX1ayRfsj-1/view?usp=sharing', 'Comets HQ', NULL, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;
insert into public.mtg_rooms (id, name, picture, location, seats, status) values ('C041', 'The Emerald Hal (4M)', 'https://drive.google.com/file/d/1mXplwnqeC2UGNdXqw8oXwRwIh89ae2qI/view?usp=sharing', 'Comets HQ', NULL, 'available') on conflict (id) do update set name = excluded.name, picture = excluded.picture, location = excluded.location, seats = excluded.seats, status = excluded.status;

commit;

-- Sanity check:
-- select id, name, location, status, seats from public.mtg_rooms order by id;